In [1]:
import math
import torch
import random
import librosa
import torchvision
import numpy as np
import pandas as pd
import torch.nn as nn
import IPython.display as ipd
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torchvision.transforms as transforms
from scipy.signal import resample

print("Import packages successfully!")

Import packages successfully!


In [20]:
x = torch.randn(2, 1, requires_grad=True)
y = torch.randn(1, 1, requires_grad=True)
z = x @ y
print(x)
print(y)
print(x.size())
print(y.size())
print("z", z)
loss = z.sum()
print("loss", loss)
loss.backward()
print(x.grad)
print(y.grad)


tensor([[0.5943],
        [0.8283]], requires_grad=True)
tensor([[0.6644]], requires_grad=True)
torch.Size([2, 1])
torch.Size([1, 1])
z tensor([[0.3948],
        [0.5503]], grad_fn=<MmBackward0>)
loss tensor(0.9451, grad_fn=<SumBackward0>)
tensor([[0.6644],
        [0.6644]])
tensor([[1.4226]])
